# Generated by Django 2.2.2 on 2019-06-26 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0011_auto_20190624_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='miniature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miniature', to='wagtailimages.Image'),
        ),
    ]
