# Generated by Django 2.2.3 on 2019-08-21 19:21

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_contactpage_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='socials',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.Social'),
        ),
    ]
