# Generated by Django 2.2.3 on 2019-08-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190821_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='link',
            field=models.URLField(default='/contact', max_length=255),
        ),
    ]
