# Generated by Django 2.2.3 on 2019-08-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_social_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='socials',
        ),
    ]
