# Generated by Django 2.2.3 on 2019-08-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_contactpage_socials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
