# Generated by Django 2.2.3 on 2019-08-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20190822_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='socials',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
